### ISSUE TITLE
None of these scripts work

### ISSUE THREAD

**Issue by 0ember1** [KibbeWater/CrabGameScripts#1]
I installed it by instruction - downloaded lastest version of python (version 3.10.0), then ran install.bat, launched scripts, but none of them are working

**Comment by KibbeWater** [comment]
could you please run them in the console by doing `py <script name>.py` and give the error you are receiving

**Comment by 0ember1** [comment]
CrabGameScripts-main\ACPatch.py", line 1, in <module>
    import pymem
ModuleNotFoundError: No module named 'pymem'
